word_anal:
	clear
	python word_analysis.py

pkg_anal:
	clear
	python pkg_analysis.py

mtx_anal:
	clear
	python matrix_analysis.py

mapping:
	clear
	python memory_mapping.py

elastic:
	clear
	python test_elastic.py